# https://www.elastic.co/guide/en/beats/heartbeat/master/heartbeat-overview.html
# Heartbeat tells you whether your services are reachable

############################# Heartbeat ######################################

# Define a directory to load monitor definitions from. Definitions take the form
# of individual yaml files.
heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: ${path.config}/monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: false
  # How often to check for changes
  reload.period: 60s

# Configure monitors inline
heartbeat.monitors:

# https://www.elastic.co/guide/en/beats/heartbeat/master/monitor-http-options.html
- type: http

  # List or urls to query
  name: kibana
  hosts: ["https://kibana"]
  ssl:
    certificate_authorities: ['/usr/share/heartbeat/certs/ca/ca.crt']
    verification_mode: certificate

  # Configure task schedule
  schedule: '@every 180s'

# https://www.elastic.co/guide/en/beats/heartbeat/master/monitor-tcp-options.html
# Query Elasticsearch

- type: tcp
  name: es01
  hosts: ["es01"]
  ports: [9200, 9300]
  ssl:
    certificate_authorities: ['/usr/share/heartbeat/certs/ca/ca.crt']
    verification_mode: certificate
  schedule: '@every 180s'

# Logstash
- type: tcp
  name: Logstash
  hosts: ["logstash"]
  ports: [5044, 9600]
  schedule: '@every 180s'

# Query DShield sensor
# For this one you can add as many has you have

- type: tcp
  name: PI
  hosts: ["192.168.25.165"]
  ports: [12222]
  schedule: '@every 180s'


#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false

#============================== Kibana =====================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:
  host: "https://kibana"
  ssl:
    certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]
    certificate: "/usr/share/heartbeat/certs/kibana/kibana.crt"
    key: "/usr/share/heartbeat/certs/kibana/kibana.key"
    verification_mode: "certificate"

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["es01:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  protocol: "https"
  ssl:
    certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]
    certificate: "/usr/share/heartbeat/certs/heartbeat/heartbeat.crt"
    key: "/usr/share/heartbeat/certs/heartbeat/heartbeat.key"
    verification_mode: "certificate"


#================================ Processors =====================================

# https://www.elastic.co/guide/en/beats/heartbeat/master/monitor-options.html

processors:
  - add_observer_metadata:
      cache.ttl: 5m
  # Optional, but recommended geo settings for the location Heartbeat is running in
      geo:
        # Token describing this location
        name: ottawa-dell-server
        country_iso_code: CA
        region_name: Ontario
        region_iso_code: ON
        city_name: Ottawa

        # Lat, Lon "
        #location: "37.926868, -78.024902"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~


#============================== X-Pack Monitoring ===============================
# heartbeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
# reporting is disabled by default.

# Set to true to enable the monitoring reporter.
monitoring.enabled: true

