# AWS
7224,AWS Direct Connect
14618,AWS Europe Public Services
16509,AWS Public Services
17633,AWS South America Public Services
# Microsoft
8075,Microsoft Corp.
8524,Microsoft Corporation
13330,Microsoft Azure
# Google
15169,Google
14416,Google
18158,Google
# IBM
3298,IBM Corporation
16779,IBM Cloud
# Oracle
2615,Oracle Global Government Solutions Inc.
14080,Oracle Corporation
# Digital Ocean
7106,Digital Ocean
14618,Digital Ocean
17455,Digital Ocean
# Linode
10928,Linode
18260,Linode
# Rackspace
6985,Rackspace US, Inc.
16205,Rackspace UK Limited
# OVH
2496,OVH SAS
3320,OVH SAS
# Hetzner
32934,Hetzner Online GmbH
19947,Hetzner Online GmbH
# Alibaba
29393,Alibaba Cloud
55367,Alibaba Cloud
55387,Alibaba Cloud
# Tencent Cloud
7823,Tencent Cloud US East RIX
8363,Tencent Cloud US West RIX
12008,Tencent Cloud Europe
65784,Tencent Cloud Mumbai
7817,Tencent Cloud Singapore
8348,Tencent Cloud Sydney
7846,Tecent Cloud Vancouver
